#! /usr/bin/env bash 

CONTAINER_RUNTIME="/usr/bin/apptainer exec" 
IMAGE="/n/fs/gen-osc/oscillator_dev/container/container_image.sif"
RUNTIME_ARGS="--pwd /projects --nv -e --bind /n/fs/gen-osc/oscillator_dev/projects:/projects"

PAYLOAD="python3 physical-diffusion-models/scripts/preprocess-mnist-v2.py"

set -ux; 
${CONTAINER_RUNTIME} ${RUNTIME_ARGS} ${IMAGE} ${PAYLOAD} 
