[project]
name = "thermoai"
version = "0.1.0"
description = "Research code for the ThermoAI project."
readme = "README.md"
requires-python = "~=3.12"
license = {file = "LICENSE"}
authors = [
  {name = "Geoffrey Roeder"},
  {name = "Cyrill Boesch"},
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["thermoai/*"]
license = "LICENSE"
readme = "README.md"
dependencies = [
    "numpy>=1.26.4",
    "scipy>=1.13.0",
    "equinox>=0.11.4",
    "optax>=0.2.3",
    "diffrax>=0.6.0",
    "pytest>=8.3.2",
]